dataset:
  path: "data/Felidae/train/"
  extension: "JPEG"
  img_size: [224, 224]

training:
  batch_size: 32
  epochs: 100
  lr: 0.001
  wandb_project: "gater for hard moe"
  best_model_path: "artifacts/"
  patience: 5
  min_delta: 0.0