dataset:
  train_path: "data/Felidae/train/"
  val_path: "data/Felidae/val/"
  extension: "JPEG"
  img_size: [224, 224]

training:
  batch_size: 32
  epochs: 50
  lr: 0.001
  wandb_project: "gater for hard moe"
  best_model_path: "artifacts/"
  model_name: "gater"
  patience: 5
  min_delta: 0.0